conversa = [
    'Oi',
    'Olá',
    'Tudo bem?',
    'Tudo ótimo',
    'Qual é seu nome?',
    'Meu nome é Fatequino',
    'Você gosta de programar?', 
    'Sim, eu programo em Python',
'Qual o horário do Professor Mario Marques às segundas?',
'Às segundas-feiras o Professor Mario Marques está na Fatec das 7:40 às 11:10',
'Qual o horário do Professor Mario Marques às terças-feiras?',
'Às terças-feiras o Professor Mario Marques nao está na Fatec, mas você pode encontrá-lo às segundas, quartas, quintas, sextas ou sábados',
'Qual o horário do Professor Mario Marques às quartas-feiras?',
'Às quartas-feiras o Professor está na Fatec das 19:00 às 22:30',
'Qual o horário do Professor Mario Marques às quintas-feiras?',
'Às quintas-feiras o Professor Mario Marques está na Fatec das 19:00 às 22:30',
'Qual o horário do Professor Mario Marques às sextas-feiras?',
'Às quintas-feiras o Professor Mario Marques está na Fatec das 9:30 às 13:00',
'Qual o horário do Professor Mario Marques aos sábados?',
'Aos sábados o Professor Mario Marques está na Fatec das 7:40 às 11:10',
'Qual o horário da Professora Adriana Marroni às segundas?',
'Às segundas-feiras a Professora Adriana Marroni está na Fatec das 7:40 às 13:00',
'Qual o horário da Professora Adriana Marroni às terças-feiras?',
'Às terças-feiras a Professora Adriana Marroni está na Fatec das 11:20 às 22:30',
'Qual o horário da Professora Adriana Marroni às quartas-feiras?',
'Às quartas-feiras a Professora Adriana Marroni nao está na Fatec, mas você pode encontrá-la às segundas ou terças',
'Qual o horário da Professora Adriana Marroni às quintas-feiras?',
'Às quintas-feiras a Professora Adriana Marroni nao está na Fatec, mas você pode encontrá-la às segundas ou terças',
'Qual o horário da Professora Adriana Marroni às sextas-feiras?',
'Às sextas-feiras a Professora Adriana Marroni nao está na Fatec, mas você pode encontrá-la às segundas ou terças',
'Qual o horário da Professora Adriana Marroni aos sábados?',
'Aos sábados a Professora Adriana Marroni nao está na Fatec, mas você pode encontrá-la às segundas ou terças',
'Qual o e-mail do professor Mario Marques?',
'O e-mail do professor Mario Marques é mario.marques@fatec.sp.gov.br',
'Quem é o coordenador do curso de Análise e Desenvolvimento de Sistemas?',
'O coordenador do curso de Analise e Desenvolvimento de Sistemas na Fatec Carapicuíba é o Ricardo Iannace',
'Quem é o coordenador de ADS?',
'O coordenador do curso de Analise e Desenvolvimento de Sistemas na Fatec Carapicuíba é o Ricardo Iannace',
'Qual o e-mail do Ricardo Iannace?',
'O e-mail do professor Ricardo Iannace é ricardoiannace@uol.com.br'
]
